### ISSUE TITLE
Рекомендации по улучшению интерфейса

### ISSUE THREAD

**Issue by ioannkozlitin** [vladdimakov/cv2#1]
Все собралось, работает :). Уже хорошая новость.
Хотелось бы, чтобы было одно окно, которое бы делилось на 4 части, а не 3 окна, как сейчас.
Кнопку сброса 1 кадра лучше взять не 'c', а, например, пробел или ввод. Так будет удобнее и интуитивно понятнее.

P.S. Дурной тон вставлять реализацию в h-файлы, если это, конечно, не шаблон. Лучше оставить в заголовочном файле заголовки, а реализацию поместить в cpp. Еще, поскольку программа на С++, то лучше все-таки использовать классы, а не глобальные функции.

**Comment by ioannkozlitin** [comment]
Рановато закрыли. Хотелось бы увидеть "чтобы было одно окно, которое бы делилось на 4 части, а не 3 окна, как сейчас". Так правда удобнее, чем потом мышкой окна растаскивать.

**Comment by vladdimakov** [comment]
Будет доделано.

**Comment by vladdimakov** [comment]
Так как разрешение моего монитора (1366x768) мало, чтобы одновременно показать 4 изображения с разрешением 640x480, я уменьшил размер окна вывода. 
Если Вам позволяет разрешение монитора, то в заголовочном файле lib.h поставьте:
const int WINDOW_WIDTH = 1280;
const int WINDOW_HEIGHT = 960;
