### ISSUE TITLE
Задание (сделать не позже 06.02)

### ISSUE THREAD

**Issue by ioannkozlitin** [vladdimakov/cv2#2]
1. Вычислить среднее фоновое изображение путем осреднения 100 (уточняется при разработке) последних кадров с учетом их взаимных смещений. Совмещение выполнить с субпиксельной точностью. Отобразить на экране.
2. Вычислить среднее отклонение по абсолютной величине от фонового изображения по тому же числу кадров в каждой точке (т.е. построить изображение средних абсолютных отклонений). Отобразить на экране после масштабирования по яркости.
3. Модифицировать п.1, обновляя только те участки среднего фонового изображения, для которых на текущем кадре отклонение от среднего фонового изображения не превышает среднего отколнения по абсолютной величине, вычисленного в п.2, умноженного на некоторую константу (не обновлять фон участками изображения, где предположительно находится объект). Константа подбирается при разработке. Разумно взять где-то 2.

**Comment by vladdimakov** [comment]
**Задание №1.**
Если при стабилизации получается изображение, имеющее отсеченные области (см. скриншот), то цвет этих областей считать черным?
![1](https://cloud.githubusercontent.com/assets/22411034/22158490/7c2a012a-df4d-11e6-9783-bc133b35239d.png)
**Задание №2.**
Что такое "масштабирование по яркости"?

**Comment by ioannkozlitin** [comment]
По 2 вопросу я уже отвечал. По первому: средний фон на текущем кадре получается из текущего кадра, на который с соответствующим смещением накладываем построенный по предыдущим кадрам средний фон. Т.е. в черной зоне должен просматриваться текущий кадр. Смысл в том, что средний фон всегда смещается так, чтобы максимально соответствовать текущему кадру, а значит его надо постоянно двигать вслед за кадром. Если не очень понятно, пишите.

**Comment by vladdimakov** [comment]
Как я понимаю, среднее фоновое изображение - это изображение, состоящее из пикселей, которые являются суммой значений пикселей на N кадрах, поделенной на N. Тогда возникает следующий вопрос. Допустим, что мы вычисляем значение пикселя, который на текущем кадре находится в "черной зоне". Тогда значение пикселя на среднем фоновом изображении будет представлять из себя: (значение_1 + ... + значение_N(черный цвет)) / N, или (значение_1 + ... + значение_N-1) / (N-1)?

**Comment by ioannkozlitin** [comment]
Пусть B(i) - фон, накопленный к i-тому кадру с учетом его самого; F(i) - i-тый кадр;
dr(i-1) - смещение F(i) кадра относительно F(i-1);
M[F,dr] - оператор смещения кадра F на dr, то есть M[F(i-1),dr(i-1)] - есть приблизительно F(i).

Если написано С := M[F,dr] (:= - это оператор присваивания, как в PASCAL), то в C меняются только те пикселы, которые имеются в смещенном изображении, а в "черной зоне" остаются старые значения C.

Тогда алгоритм таков:
1. С := F(i)
2. С := M[B(i-1),dr(i-1)]
3. B(i) := (1-alf) * C + alf * F(i)

alf - коэффициент обновления, в нашем случае ~ 0.01.

В таком варианте черных зон не возникает.

**Comment by vladdimakov** [comment]
Выполнил первое задание (кроме субпиксельной точности). Отнюдь не уверен, что правильно, но следовал Вашему псевдокоду. Результат выполнения выводится в нижнюю правую часть окна. Буду очень ждать Вашего мнения о работе. 

Не совсем понятно, как добиться субпиксельной точности при формировании среднего фонового изображения по алгоритму, описанному выше, так как каждый кадр мы смещаем на dr (очевидно, что это целое значение). Возможно, просто необходимо "копить" небольшие смещения до целого значения, а как только "накопленное" значение достигнет 1 (или более), то выполнять смещение?

**Comment by ioannkozlitin** [comment]
Лукас-Канаде дает вообще-то нецелые смещения.

**Comment by vladdimakov** [comment]
Согласен. Я имею в виду сам процесс наложения кадров.

**Comment by ioannkozlitin** [comment]
Для нецелых смещений используется билинейная интерполяция.

**Comment by ioannkozlitin** [comment]
Вроде работает, но не покидает ощущение, что что-то не то... Возможно неправильно смещается средний фон перед осреднением.

**Comment by ioannkozlitin** [comment]
Знак смещения поменял на противоположный - на вид стало лучше. Надо над этим подумать, как правильно двигать. Кстати, среднее изображение надо хранить ии обрабатывать во float, а при выводе преобразовывать к uchar - куда лучше будет работать. Посмотрите.

**Comment by ioannkozlitin** [comment]
Позитивненько. Только не нравится грязь на линейке, где FPS показывается. Неплохо бы теперь сделать субспиксельное смещение с помощью билинейной интерполяции.

**Comment by ioannkozlitin** [comment]
Еще: REFRESH_RATE лучше все-таки в main.cpp вернуть и сделать передаваемым параметром.

**Comment by vladdimakov** [comment]
1. Под грязью на линейке, где показывается FPS, Вы имеете в виду, что "смазывается" сам шрифт?
Если это так, то причиной является то, что я масштабирую окно, чтобы оно умещалось на экране ноутбука. Если иметь экран с большим расширением и убрать масштабирование окна, то грязи нет.
Предлагаю пока оставить так, ибо возможности иметь другой монитор у меня нет. Но я попробую немного поменять шрифт, чтобы смотрелось чуть аккуратней.
2. Не совсем понимаю, как использовать билинейную интерполяцию для субпиксельного смещения. Ведь билинейная интерполяция, грубо говоря, позволяет нам узнать значение точки P=(x,y), используя опорные точки Q11, Q12, Q21, Q22. Не понимаю, как связать это со смещением.

![bilinear_interpolation](https://cloud.githubusercontent.com/assets/22411034/22396188/f8f25d12-e563-11e6-9290-e8daf7e7ef53.png)

**Comment by vladdimakov** [comment]
3. Выполнил задание №2, жду Вашего мнения. 
По какому принципу стоит выбирать коэффициент масштабирования яркости (scalingFactor в main)?

4. Немного покопался в интернете. Я так понимаю, что результатом выполнения данного issue станет нечто похожее на https://www.youtube.com/watch?v=i4sPR3bjP8I.

**Comment by ioannkozlitin** [comment]
1. Горизонтальная полоска с FPS должна быть равномерно закрашена, а она заполнена каким-то мусором, т.е. дело не в шрифте, а в фоне. 

2. D(x+dx,y+dy) = S(x,y) * (1-dx)*(1-dy) + S(x+1,y) *dx * (1-dy) + S(x,y+1) * (1-dx) * dy + S(x+1,y+1) * dx * dy
Здесь  0 <= dx <= 1 и 0 <= dy < 1 - нецелое смещение. 

Эта формула выполняет субпиксельный сдвиг S и помещает результат в D, Впрочем, в OpenCV  cкорее всего есть готовая функция для этого, например в IPP она называется CopySubpix.

3. Коэффициент выбирается на глазок с тем расчетом, чтобы можно было разглядеть результат.

4. Там стабилизатор, хотя я до конца не смотрел, а у нас осреднение фона.

**Comment by ioannkozlitin** [comment]
Результат похож на правду, но надо еще "погонять" прогу, чтобы в этом убедиться. Смущает то, что очень быстро накапливается абсолютная разность - это подозрительно.

**Comment by ioannkozlitin** [comment]
Надежды на улучшение ситуации со скоростью накопления абсолютной разности при использовании субпиксельной обработки оправдались - она дала ощутимый эффект.

Из неприятного: при резком изменении положения камеры программа вылетает - где-то ошибка, скорее всего выход за пределы индекса какого-то массива.

**Comment by ioannkozlitin** [comment]
Лучше коэффициент обновления увеличить до 0.1 - в данных условиях результат выглядит много лучше. Далее пора переходить к 3 заданию. Там есть некоторые тонкости реализации, о которых я Вам расскажу позднее, когда Вы реализуете основной функционал.

**Comment by ioannkozlitin** [comment]
Думаю, нашел у Вас ошибку: если даже участок фона не обновляется он все равно должен сдвигаться вслед за текущим кадром, а не оставаться на месте, как у Вас. Я попробовал исправить эту ошибку, и, думаю, мне это удалось. Посмотрите. Потом у Вас маска, по-моему, работает с точностью до наоборот. Проверьте. Где сильное изменение, там мы фон НЕ ОБНОВЛЯЕМ. Просьба: выведите маску в 4 окно: где 0 - значение 0, где не 0 - значение 255. Для отладки.

**Comment by ioannkozlitin** [comment]
Программа при резком смещении камеры больше не вылетает.

**Comment by vladdimakov** [comment]
То есть в случае, если кадр не обновляется, а просто сдвигается, мы выполняем следующий алгоритм?
1. С := F(i)
2. С := M[B(i-1),dr(i-1)]
3. B(i) := C

**Comment by ioannkozlitin** [comment]
Точно

**Comment by ioannkozlitin** [comment]
Завтра постараюсь посмотреть.

**Comment by vladdimakov** [comment]
**Насчет маски.**
Где сильное изменение, там маска имеет значение 0, следовательно эта область не обновляется. Вроде бы, это соответствует логике. 

**Реализовал алгоритм работы следующим образом.**
1. С := F(i)
2. С := M[B(i-1),dr(i-1)]
3. F(i) := Q[F(i), C]  
4. B(i) := (1-alf) * C + alf * F(i)

Где Q[F, C] - оператор наложения изображений по следующему правилу:
Q[F, C] = F, в области, где изменение НЕ СИЛЬНОЕ
Q[F, C] = C, в области, где изменение СИЛЬНОЕ

**Comment by ioannkozlitin** [comment]
Отдыхайте. Хватит на сегодня.

**Comment by ioannkozlitin** [comment]
Вроде логика у Вас правильная, надо еще прогу погонять.

**Comment by ioannkozlitin** [comment]
Есть 2 пожелания:
1. Передавать имя файла для воспроизведения в качестве параметра командной строки. Если есть - открываем видео, нет - запускаем камеру.
2. Видео лучше "зациклить", т.е. после окончания воспроизведения последнего кадра начинать опять с первого.

**Comment by ioannkozlitin** [comment]
У меня 2 замечания по алгоритму:

1. Изображение среднего абсолютного отклонения должно двигаться от кадра к кадру так же, как и среднее фоновое изображение, поскольку они вместе образуют модель фона (т.е. его надо тоже двигать вслед за кадром, причем с субпиксельной точностью).

2. Изображение среднего абсолютного отклонения не должно обновляться там, где есть объект, поскольку является характеристикой средней изменчивости фона (т.е. его надо также обновлять по маске).

**Comment by vladdimakov** [comment]
Простите за временное отсутствие. Прохожу медосмотры для военных сборов, что занимает уйму времени. 

Исправил все замечания, но остается немного непонятным следующий вопрос о количестве используемых масок.

Наш алгоритм работает следующим образом:
1. Строим изображение среднего абсолютного отклонения (используя среднее фоновое изображение)
2. Строим среднее фоновое изображение (используя изображение среднего абсолютного отклонения)

В обоих случаях используем маски, для обновления только тех областей, где изменения наиболее сильные. Целесообразно ли использовать 2 маски? Или можно обойтись одной и той же?
На мой взгляд, результат лучше при использование двух разных масок. Т.к. изображение среднего абсолютного отклонения обновляется с учетом предыдущего среднего фонового изображения, следовательно нужна первая маска. Далее новое фоновое изображение строится с учетом изображения среднего абсолютного отклонения, на что требуется вторая маска. Эти маски на деле почти совпадают, но результаты отличаются довольно значимо. 

На example.mp4 можно увидеть, что результат стал лучше. Но появилась новая проблема, решение которой пока не пришло мне в голову: при движении камеры на масках появляются шумы, что влечет за собой значительное ухудшение "адекватности" фонового изображения. Как можно пофиксить данную проблему?

**P.S**. Прошу закрыть глаза на сырость кода в переработанных функциях, я просто хочу найти наилучший вариант и оптимизировать его.

**Comment by ioannkozlitin** [comment]
Я использовал 1 маску и у меня таких проблем не возникало. Здесь проблема в старте модели. Я ее решал так: изначально заполнял изображение средних отклонений числом 255. Им же заполнял неизвестные мне части этого изображения при его сдвиге. Это приводит к тому, что изначально обновляется вообще весь экран, а потом, когда модель настроится, она подстраивается под особенности реального фона.

**Comment by vladdimakov** [comment]
Исправил все согласно вашим советам. Стало гораздо лучше. Жду следующих заданий и пожеланий)

**Comment by ioannkozlitin** [comment]
Кажется я понял в чем дело.

У Вас написано в deviationFromAverageBackImg:
currentDeviationImg = abs(currentFrame - averageBackImg);

А надо вычитать из текущего кадра среднее изображение С УЧЕТОМ СМЕЩЕНИЯ.

**Comment by ioannkozlitin** [comment]
При вычислении маски, похоже, та же проблема.

**Comment by vladdimakov** [comment]
Какова последовательность выполнения операций? Сейчас она следующяя: 
1. Смещаем среднее фоновое изображение и изображение среднего абсолютного отклонения
2. Вычисляем маску областей, где изменения сильные (движущийся объект)
3. Вычисляем среднее фоновое изображение 
/* Тут модель фона изменяется, и маска, вычисленная ранее, уже не столь хорошо взаимодействует с моделью фона, т.к. среднее фоновое изображение было вычислено после нахождения маски */
4. Вычисляем изображение среднего абсолютного отклонения

**Comment by vladdimakov** [comment]
Подправил логическую ошибку, о которой Вы говорили. Получил очень странный результат:
1. Изображение среднего абсолютного отклонения и среднее фоновое изображение не отображают движущиеся объекты, что хорошо.
2. Со временем шум поглощает почти всю маску и изображение перестает обновляться полностью, а не только движущимися частями, что очень плохо.

**Comment by ioannkozlitin** [comment]
Проблема частично решается увеличением deviationFactor. Может какие-то логические ошибки есть. Надо смотреть.

**Comment by ioannkozlitin** [comment]
Да, среднее абсолютное отклонение лучше вычислять в п.4 по старому среднему фону, а не по измененному.

**Comment by vladdimakov** [comment]
После всех исправлений программа стала работать довольно хорошо. Посмотрите работу на example.mp4. Сейчас сделаю видео с перемещением камеры.

**Comment by ioannkozlitin** [comment]
Второе мое замечание по поводу обновления среднего абсолютного отклонения все-таки учтите.

**Comment by vladdimakov** [comment]
Это замечание?
"Изображение среднего абсолютного отклонения не должно обновляться там, где есть объект, поскольку является характеристикой средней изменчивости фона (т.е. его надо также обновлять по маске)"
Я его учел, оно также обновляется по маске. Надо просто немного подождать, пока изображение окончательно сформируется.

**Comment by ioannkozlitin** [comment]
Имеется в виду "среднее абсолютное отклонение лучше вычислять в п.4 по старому среднему фону, а не по измененному"

**Comment by vladdimakov** [comment]
А, это тоже учел. 
Там же следующий порядок операций:
```
currentDeviationImg = abs(currentFrame - averageBackImg);
averageBackImg = (1 - refreshRate) * averageBackImg + refreshRate * currentFrameStaticPart;
deviationImg = (1 - refreshRate) * deviationImg + refreshRate * currentDeviationImgStaticPart;
```
То есть я запоминаю currentDeviationImg, а только потом строю новое averageBackImg.

**Comment by ioannkozlitin** [comment]
Да, осталось поставить порог на вывод окончательного результата. Строится он абсолютно точно также, как и маска, только множитель надо другой поставить, видимо побольше. Лично мне нравится белая цель на черном фоне, хотя это и не принципиально. Результат можно поместить там, где сейчас отображается маска.

**Comment by vladdimakov** [comment]
Сделал вывод окончательного результата.

**Comment by ioannkozlitin** [comment]
Теперь надо убедиться, что результат будет не хуже при движении камеры. Дальше надо добавить глобальную фильтрацию шумов. Как именно - потом напишу.

**Comment by vladdimakov** [comment]
Тогда сейчас займусь тестовым видео.

**Comment by ioannkozlitin** [comment]
Можно ускорить стартовую инициализацию модели, если вместо 255 заполнять среднее отклонение величиной 256/movingTargetFactor.

**Comment by ioannkozlitin** [comment]
Вообще, вынесите константу заполнения наверх.

**Comment by vladdimakov** [comment]
Наверх в main.cpp?

**Comment by ioannkozlitin** [comment]
Именно.

**Comment by ioannkozlitin** [comment]
Все хорошо, только константа movingTargetFactor у Вас великовата. Впрочем, после удаления шумов, ее, скорее всего, можно будет уменьшить.

**Comment by ioannkozlitin** [comment]
У меня и без глобального фильтра удовлетворительно работает с константой 4, так что что-то там еще у Вас сидит...

**Comment by ioannkozlitin** [comment]
Имеется в виду тот код, который я залил.

**Comment by ioannkozlitin** [comment]
На вашем example4

**Comment by ioannkozlitin** [comment]
Со смещением камеры нормально работает. Большие ошибки в конце, скорее всего, из-за перспективы, которую мы не учитываем.

**Comment by vladdimakov** [comment]
Возможно, излишняя зашумленность в моей программе связана с функцией билинейной интерполяции. Попробую погонять разные варианты. 

Как у Вас появится свободное время, опишите, пожалуйста, дальнейшее задание.

**Comment by ioannkozlitin** [comment]
Возможно у Вас все нормально. Там есть один ньюанс, просто я сегодня не успел проверить.

**Comment by vladdimakov** [comment]
У меня появилась идея распараллелить вычисления в функциях с помощью многопоточности C++11 для прироста производительности. Уж очень сильно проседает FPS. Стоит ли?

**Comment by ioannkozlitin** [comment]
Пока, думаю, не стоит. Если хотите оптимизировать, попробуйте сперва улучшить сам алгоритм: убрать повторяющиеся действия, не тратить время на выделение памяти и последующее ее освождение, а выделить все зарание и не трогать, вместо самописных кусков использовать готовое из openCV и т.п.

**Comment by ioannkozlitin** [comment]
Сейчас немного работы привалило, как разбирусь с этим - напишу что дальше делать.

**Comment by ioannkozlitin** [comment]
Можете попробовать сделать сегментацию, окружить каждый сегмент прямоугольником и отобразить эти прямоугольники в 1 окне (где исходный кадр).

**Comment by ioannkozlitin** [comment]
Еще можете перед выводом итогового (в 4 окне) изображения на экран прогонять его через глобальный фильтр, отсекая все точки, которые меньше определенного порога. Делать это надо, конечно, до бинаризации. Порог считаем по глобальной гистограмме _histogram изображения так:
```


int DiffImageFilter::getBackgroundBound()
{
	int startInd = 1;
	if(_histogram[0] <= _histogram[1])
	{
		for(startInd = 1; startInd < 256; startInd++)
		{
			if(_histogram[startInd+1] < _histogram[startInd])
			{
				break;
			}
		}
	}
        int endInd = 1;
	for(endInd = startInd; endInd < 256; endInd++)
	{
		if(_histogram[endInd+1] >= _histogram[endInd])
		{
			break;
		}
	}
    return endInd;
}

```

**Comment by vladdimakov** [comment]
Как я понял, функция getBackgroundBound() возвращает значение по следующему правилу:
![img_5736](https://cloud.githubusercontent.com/assets/22411034/23104050/1ce01622-f6d7-11e6-925f-e5ba393b6bbf.jpg)
Пока не очевидно, почему именно это значение является границей фоновых яркостей. 
**По какому изображению необходимо строить гистограмму?**

**Comment by ioannkozlitin** [comment]
По тому, которое получается после вычитания из текущего кадра среднего фона. Неочевидно - конечно, но это получено опытным путем.

**Comment by vladdimakov** [comment]
Спасибо. То есть алгоритм работы получается следующим: 
1. Нахожу изображение среднего абсолютного отклонения текущего кадра:
`currentDeviationImg = abs(currentFrame - averageBackImg);`
2. Нахожу маску неподвижной части изображения:
`frameStaticPartMask = movingTargetFactor * deviationImg - currentDeviationImg;`
3. Нахожу порог яркостей фона (backgroundBound) по гистограмме, построенной на основе currentDeviationImg.
4. Пиксели currentDeviationImg, значения которых меньше порога backgroundBound обозначаю в маске frameStaticPartMask, как фон.

P.S. В последнем коммите уже есть реализация этого алгоритма.

Сегментация в данном случае представляет собой выделение прямоугольниками областей, которые отображаются на итоговом изображении (в 4 окне) белым цветом (движущиеся области)?

**Comment by ioannkozlitin** [comment]
Все хорошо, только fps просел. Видимо из расчета гистограммы. Поищите встроенную функцию OpenCV для этого - скорее всего через нее будет побыстрее работать. Про сегментацию - да, именно так.

**Comment by vladdimakov** [comment]
Готовую я нашел, но я потихоньку начинаю переходить от готовых функций к своим реализациям. Так что подумаю, как сделать свою реализацию более быстрой. 

А ведь данный метод (с гистограммой и поиском порога) можно использовать не только при выводе результата, но и при вычислении маски для среднего фонового изображения и изображения абсолютного отклонения. Не так ли?

**Comment by ioannkozlitin** [comment]
Можно, конечно, но, думаю, большой разницы не будет. Сконцентрируйтесь лучше на сегментации.

**Comment by vladdimakov** [comment]
Хорошо.

**Comment by ioannkozlitin** [comment]
Работает заметно быстрее :)

**Comment by vladdimakov** [comment]
Идея по сегментации следующая:
1. Разбить движущиеся точки на кластеры на основе евклидовой метрики.
2. Вычислить границы кластеров и на их основе построить прямоугольники.

Это правильная идея?

**Comment by ioannkozlitin** [comment]
Найти связные области, объединить те, которые близко лежат, окружить то, что получится, прямоугольниками.

**Comment by ioannkozlitin** [comment]
Хорошо, я видел, что все работает.

**Comment by vladdimakov** [comment]
Сегодня сделаю алгоритм сегментации более читабельным и оптимизирую его.

**Comment by vladdimakov** [comment]
Доделал сегментацию, жду дальнейших указаний :) 

**P.S. Поздравляю Вас с праздником!**

**Comment by ioannkozlitin** [comment]
И Вас с праздником! Отдыхайте пока. Можете про CART деревья почитать - пригодится.

**Comment by vladdimakov** [comment]
Опишите, пожалуйста, дальнейшее задание, если у Вас появится свободное время)

**Comment by ioannkozlitin** [comment]
Да, я понимаю. Немного разружен по работе. Скоро напишу. Хорошо, что беспокоитесть :)

**Comment by vladdimakov** [comment]
Хорошо)

**Comment by ioannkozlitin** [comment]
Дальше занимаемся распознаванием. Обучаем по 2 группам примеров: положительному (наша машинка) и отрицательным (случайные прямоугольники вне машинки). Строим классификатор. Для этого прогоняем по всему видео. Потом сперва на том же, а потом и на другом (но похожем) видео ищем "машинкоподобные" объекты. Смотрим, как он их обнаруживает. Окно (размер и соотношение сторон) для начала задаем сами. Для обнаружения пробегаем этим окном по всей картинке. Это концептуально. Как строить классификатор тебе расскажет Алексей Федотов, который работает у нас под моим началом. Он учится в МИЭТе на год старше. Могу и я рассказать, но я это не реализовывал, а он знает все тонкости. Чуть позже я вас познакомлю.

**Comment by vladdimakov** [comment]
Тогда пока я почитаю про классификацию и CART. И буду ждать от Вас вестей.

**Comment by ioannkozlitin** [comment]
Добавил материал для прочтения. Наш классификатор будем делать на основе статьи "On-line Random Forests".

**Comment by vladdimakov** [comment]
Иван Алексеевич, а правильно ли я понимаю общую суть классификации в нашем случае? Мы строим дерево решений на основе обучающей выборки, задав принадлежность элементов требуемым классам. После чего применяем полученное дерево решений к другой выборке, классифицируя ее элементы.

**Comment by vladdimakov** [comment]
Добился от github полной версии с приватными репозиториями для нужд образования. Все ли нормально с уведомлениями на почту?  

Появился еще один бумажный вопрос (возможно, Вам об этом уже писала Виктория). Нужна ваша подпись на утверждение темы ВКР. Как это будет удобней для Вас организовать?
Сам документ прилагаю на всякий случай. ([zayavlenie_vypusknika_na_utverzhdenie_VKR.docx](https://github.com/vladdimakov/cv2/files/817226/zayavlenie_vypusknika_na_utverzhdenie_VKR.docx))
