### ISSUE TITLE
Распознавание

### ISSUE THREAD

**Issue by ioannkozlitin** [vladdimakov/cv2#3]
Обучаем классификатор

**Comment by vladdimakov** [comment]
Как лучше искать признаки на изображении?
1. Случайно генерируем координаты окна признака (например, окна 10x10).
2. Ведем учет количества попаданий в фон (N1) и выделенную область цели (N2).
3. На основе вычисленных значений признаков и величин N1, N2 строим классификатор (Разделяем очередную вершину, если N1 + N2 > L, где L - некоторый порог накопления статистики. После чего выбираем наилучший признак по индексу Gini).

Или
1. Случайно генерируем N1 координат окна признаков для фона и N2 координат внутри выделенной области цели.
2. На основе вычисленных значений признаков и величин N1, N2 строим классификатор (Разделяем очередную вершину, если N1 + N2 > L, где L - некоторый порог накопления статистики. После чего выбираем наилучший признак по индексу Gini).

**Comment by ioannkozlitin** [comment]
У меня на dashboard не было уведомления о Вашем последнем сообщении, так что разбирайтесь. Опять добавил проект в watch, может поможет.

**Comment by ioannkozlitin** [comment]
Не вполне понимаю Ваш вопрос, разверните его подробнее, особенно его предысторию.

**Comment by vladdimakov** [comment]
Иван Алексеевич, мы решили встретиться с Алексеем на неделе, чтобы уточнить непонятный мне момент. 

К Вам тогда другой вопрос:
Как Вы писали в предыдущем issue, мы обучаем классификатор в течении всей длины видео, а потом с помощь него находим требуемый объект на другом видео. То есть обученный лес решений нужно сохранять в какой-то файл для последующего использования? Или я неправильно понимаю нашу концепцию?

**Comment by ioannkozlitin** [comment]
Думаю да. Второй вариант: сначала прогнать обучающее видео, а потом сразу тестовое, но тогда придется каждый раз ждать окончания обучения.

**Comment by vladdimakov** [comment]
С построением классификатора я разобрался, но при обучении возникает одна проблема:
Как указать где именно находится цель на подобном изображении?
![1](https://cloud.githubusercontent.com/assets/22411034/23998801/4e1b88ea-0a67-11e7-93df-0034fec418b6.jpg)
Необходимо как-то отсечь области, обведенные красным? Ведь очевидно, что в этих областях нет требуемой цели.
Как это лучше реализовать?

**Comment by ioannkozlitin** [comment]
Думаю, надо делать первичный захват вручную (т.е. на 1 кадре указать прямо на цель), а затем на каждом следующем кадре по траекторным признакам и соотношению сторон выбрать нужный объект.

**Comment by vladdimakov** [comment]
А что такое "тракторные признаки"?
И нельзя ли просто искать ближайший объект на следующем кадре?

**Comment by ioannkozlitin** [comment]
Это собственно и имеется в виду. Просто я сейчас отчет на работе пишу, поэтому так и изъясняюсь...

**Comment by vladdimakov** [comment]
Понял)

**Comment by vladdimakov** [comment]
Реализовал классификатор. Теперь надо его настроить и отладить. Появились следующие вопросы.
1. На каждом кадре я определяю N областей фона (случайного размера и случайного положения). Какую величину N разумно взять и какие ограничения на размер областей выбрать?
2. Сколько признаков лучше использовать для каждой выделенной области (в том числе и цели)
3. В дереве решений я разделяю вершину на два потомка, как только накоплено некоторое число статистик M = N1 + N2 (где N1 - число векторов с признаками из фоновых областей, N2 - число векторов с признаками цели). Какое число M разумно выбрать?

Я понимаю, что все эти константы подбираются опытным путём, но, возможно, у Вас есть какие - то мысли по этому поводу.

**Comment by vladdimakov** [comment]
Иван Алексеевич, здравствуйте. Несколько дней отлаживал алгоритм, пытаясь добиться хороших результатов и думал, как все лучше организовать. Стали очевидными следующие проблемы:
1. Для адекватного нахождения классификатором целей необходимо использовать довольно продолжительное видео на стадии обучения.
2. Предложенную Вами концепцию "проходить окном по всему кадру при нахождении цели" почти нереально организовать даже близко к realtime, или же результаты получаются не самыми лучшими, т.к. необходимо изменять размер самого окна, тем самым уточняя координаты цели.

Но решение этих проблем нашлось довольно просто. Прочитав еще раз теорию по сегментации на основе классификатора (в особенности kalal-long_term_tracker-olcv09.pdf, загруженный Вами), мне пришла в голову идея немного изменить ту концепцию, которую Вы предлагали. Опишу вкратце алгоритм работы конечной программы, как я его вижу.
1. У нас есть две составляющие части программы: детектор (сегментатор) и классификатор.
2. Начинается работа программы, начинает работать детектор, который продолжает свою работу **на протяжении всей работы программы**.
3. Программа предлагает пользователю выбрать цель (одну из найденных детектором областей). Пользователь кликом мышки выбирает нужную область.
4. Начинается процесс обучения классификатора, который продолжается N кадров (подберем это значение опытно).
5. По прошествии N кадров классификатор сам выделяет область цели (из числа областей, выделенных детектором на текущем кадре) и продолжает обучаться.
6. На каждом следующем кадре классификатор вновь находит цель (из числа областей, выделенных детектором на текущем кадре) и далее обучается.

Таким образом, с каждым кадром классификатор все лучше и лучше может находить необходимую цель, а ресурсоемкий процесс поиска положения цели упрощается, т.к. число областей, выделенных детектором, не столь большое. При всем этом мы не теряем все преимущества, которые дает нам классификатор (например, вновь обнаруживать цель, если она пропала из зоны видимости, а затем вернулась)

Жду Вашего мнения на все вышеописанное.

**Comment by ioannkozlitin** [comment]
Мы к этому, собственно, и стремились. Только планировалось это в конце работы. Сначала было желание построить хороший классификатор, а потом делать то, что Вы написали. Я бы на данном этапе хотел посмотреть работу классификатора самого по себе и плевать пока на реальное время. Как я могу посмотреть того, что Вы уже сделали?

**Comment by ioannkozlitin** [comment]
Вы мне напишите инструкцию, как использовать Вашу прогу. Кстати, Вы интегральные изображения используете?

**Comment by vladdimakov** [comment]
Да, интегральные изображения. 
Я залью новую версию классификатора 
(со всеми исправлениями) и напишу инструкцию только к вечеру, так как сегодня допоздна в университете.

**Comment by vladdimakov** [comment]
**Инструкция по использованию программы.**
Есть 2 параметра консоли:
1. Режим работы программы: t - обучение классификатора, c - режим классификации (нахождения целей).
2. Название видео: example1.mp4, example2.mp4.

**При выборе режима обучения классификатора.**
Задать первый параметр консоли - t, а вторым параметром указать название видео.
Навести курсор и кликнуть на машинку в окне №1, как только она полностью появится в кадре:
![image](https://cloud.githubusercontent.com/assets/22411034/24265478/c1191274-1014-11e7-8f5a-5f47b087ab6d.png)
Вокруг машинки появится рамка:
![image](https://cloud.githubusercontent.com/assets/22411034/24265507/d97620be-1014-11e7-8412-7c72f8ece951.png)
Далее необходимо дождаться окончания обучения классификатора (в консоли появятся сообщения о том, что деревья записаны в файл).

**При выборе режима классификации (нахождения целей).**
Задать первый параметр консоли - c, а вторым параметром указать название видео.
В консоли появятся сообщения о том, что деревья считаны из файла.
Далее придется "наслаждаться" не самым хорошим результатом работы программы, т.к. деревьев использовано **очень мало** (иначе FPS падает до < 0.1 при полном прохождении плавающего окна по кадру)(при количестве деревьев ~ 20 результат очень достойный, но это возможно только при использовании классификатора в паре с детектором).

**Можно комбинировать видео:**
Обучать на одном, а наблюдать результат на другом. Это довольно показательно.

**Comment by vladdimakov** [comment]
Жду Вашей рецензии на проделанную работу, чтобы продолжить разработку.

**Comment by ioannkozlitin** [comment]
Посмотрел-таки наконец, как работает классификатор. Думаю проблема в том, что размер квадрата не соответствует размеру цели. Правда не очень понятно, как это поправить, ведь заранее этот размер не известен. Хорошо то, что по крайней мере настоящую цель он обычно находит. А так все позитивно.

**Comment by vladdimakov** [comment]
То есть я могу приступить к реализации "обучения на лету"?

**Comment by ioannkozlitin** [comment]
Думаю да.

**Comment by vladdimakov** [comment]
Иван Алексеевич, я никак не могу разобраться с одним теоретическим моментом. Очень нужна Ваша помощь.
Я начал реализовывать алгоритм "обучения на лету" согласно работе saffari_olc_09.pdf. В следующем абзаце мне не понятно, как генерируется значение k, согласно распределению Пуассона.
![image](https://cloud.githubusercontent.com/assets/22411034/24718568/224a6e6a-1a3f-11e7-8cfa-b2ef79062a8a.png)
Поискав в оригинальной статье ozru01a.pdf больше полезной информации по этому поводу, я нашел только следующее:
![image](https://cloud.githubusercontent.com/assets/22411034/24719010/ce54482e-1a40-11e7-84ee-14fc23a8d187.png)
Откуда не стало более понятно, как же вычислить эту k.

**Comment by vladdimakov** [comment]
Решение вопроса, описанного ранее, нашлось. Сам вопрос я удалил, чтобы Вы не тратили время на его прочтение.

**Comment by vladdimakov** [comment]
Иван Алексеевич, я закончил реализацию алгоритма обучения классификатора "на лету". Результат в последнем коммите.
 
**Инструкция.**
Аргумент командной строки - один - название видео (лучше выбирать example2.mp4, т.к. для него я подобрал довольно оптимальное число кадров для обучения).
Как только машинка появляется в кадре - кликаете на нее, после чего она выделяется рамкой.
Как только закончится обучение (~100 кадров), программа сама начнет находить цель и дообучаться.

**Финальная концепция работы программы.**
При реализации я использовал все идеи, предложенные в статье saffari_olc_09.pdf, что дало крайне положительный результат (я строил графики ошибки классификации, так называемой OOB ошибки, и сравнивал результаты). После чего я провел серию опытов, изменяя параметры работы классификатора, и нашел следующую, довольно ожидаемую проблему. Если при обучении в классификатор подавать примеры, где машинка видна только с одной стороны, то в случае ее поворота на >90 градусов, он почти перестает находить ее. Поэтому предлагаю следующую, финальную концепцию работы программы (опишу ее тезисно).
1. Детектор активен на протяжении всей работы программы и осуществляет сегментацию.
2. Поиск цели осуществляется только по сегментированным областям.
3. В случае, если классификатор не находит цель на кадре (например, машинка повернулась на >90 градусов или изменилось освещение), начинается работа вспомогательного алгоритма.
4. **Принцип работы вспомогательного алгоритма (если цель на данном кадре не найдена классификатором).** Алгоритм берет за основу координаты цели, найденные на прошлом кадре **классификатором** и находит наиболее подходящую область среди областей, найденных на данном кадре **детектором** (сверяет по траекторным признакам и соотношению сторон). После чего детектор указывает классификатору на то, что цель находится в найденной области. Если же подобной области не найдено (цель исчезла из зоны видимости), то **классификатор** переходит в режим ожидания появления цели.

Данная концепция хорошо работает, хоть и способна привести к временному выделению неправильной цели. Но эта ошибка довольно быстро компенсируется работой классификатора.

Жду Вашего мнения. В случае, если Вас устроит моя концепция, то я доделаю наш проект на этой неделе.

**Comment by ioannkozlitin** [comment]
Да, думаю это пойдет. Можно подумать, как лучше сделать, но для диплома и этого хватит.

**Comment by vladdimakov** [comment]
Есть множество статей с идеями, как сделать это лучше, но все подходы довольно долгие в реализации. Я думаю, что стоит оставить это до магистерской работы, а пока доработать существующий проект.

**Comment by vladdimakov** [comment]
Закончил реализацию предложенной мной концепции. Если Вас устраивает работа программы, то работу над ней можно считать оконченной, и более плотно переходить к написанию текста ВКР.
Порой программа не находит цель (~4-6% кадров, в наибольшей степени из-за изменения освещенности, когда у машинки включаются фары), но эта проблема будет решена следующим образом. Когда в последней главе ВКР ("Описание результатов") я буду строить графики ошибки нахождения цели и ошибки работы классификатора, я по большому числу накопленной статистики проведу процедуру минимизации ошибки с помощью стандартной функции MATLAB fminsearch() и определю тем самым оптимальные параметры. Это довольно часто встречающийся подход.

Жду Вашего мнения о работоспособности нашей программы и о том, можно ли работу над ней считать оконченной (за исключением подбора параметров классификатора). Есть ли какие-то замечания по интерфейсу?

**Comment by ioannkozlitin** [comment]
Я пока не смотрел, но можете уже плотно работать над дипломом. Ничего существенного в коде мы делать уже не будем. Как посмотрю - отпишусь.
