### ISSUE TITLE
Текст ВКР

### ISSUE THREAD

**Issue by vladdimakov** [vladdimakov/cv2#4]
Пишем и редактируем текст ВКР.

**Comment by vladdimakov** [comment]
Иван Алексеевич, как Вы думаете, стоит ли снять еще одно тестовое видео для нашего проекта? Мне кажется, что для демонстрации всех достоинств и недостатков (для создания скриншотов в тексте ВКР),  необходимо иметь видео, от которого требуется:
1. Иметь продолжительность ~3-5 минут
2. Имеет участки, где цель исчезает из зоны видимости
3. Иметь участки, где цель частично перекрывают другие объекты
4. Иметь участки, где камера движется (порядка 20% от общей длины видео)
5. Иметь участки с незначительным и значительным изменением освещенности цели
6. Иметь участок, с несколькими подвижными целями 

Если есть еще какие то аспекты, которые стоит продемонстрировать, опишите их, пожалуйста.
Вообще, движение машинки по коридору - нормальное тестовое видео для ВКР? А то меня немного смущает некоторая несерьезность. У меня есть возможность снять эту же машинку в большом офисном помещении, чтобы траектория ее движения была более плавной, а не похожей на поступательные движения вперед-назад.

**Comment by ioannkozlitin** [comment]
Хуже от этого точно не будет. Так что дерзайте.

**Comment by vladdimakov** [comment]
Написал отчет по производственной практике.  Темой выбрал: "Разработка классификатора объектов, присутствующих на цифровой видеозаписи". Посмотрите, пожалуйста, все ли хорошо  (просто просмотрите по диагонали). Документы конвертировал в pdf, чтобы Вы их могли просмотреть непосредственно с гита.
[Дневник практики.pdf](https://github.com/vladdimakov/cv2/files/966932/default.pdf)
[Отчет по производственной практике.pdf](https://github.com/vladdimakov/cv2/files/966933/default.pdf)
Могу ли я подъехать во вторник в послеобеденное время к Вам на работу, чтобы их подписать?

**Comment by ioannkozlitin** [comment]
Можете, телефон дома, так что все сюда.

**Comment by vladdimakov** [comment]
Хорошо. Подъеду к Вам примерно в 14:30. Как буду на месте - напишу сюда

**Comment by ioannkozlitin** [comment]
понял

**Comment by vladdimakov** [comment]
Жду Вас на проходной

**Comment by vladdimakov** [comment]
Иван Алексеевич, добрый день. Настало время разобраться с вопросами, которые я не смог решить сам.  Очень жду вашей помощи!

**Вопрос №1.**
Как я понимаю, в окончании текста ВКР следует показать насколько хорошо работает наш алгоритм. Предлагаю сделать это путем вычисления двух типов ошибок.
1. **Ошибка классификатора.** Вычисляется методом OOBE, который работает следующим образом. 
В основе алгоритма построения леса лежит метод, называемый baging. Он предполагает, что каждое дерево строится на основе бутстреп выборки (т.е. выборки с возвращением) из исходной обучающей выборки. Таким образом некоторые примеры (вектора признаков) вообще не участвуют в построении деревьев (обозначим такие примеры S). Примеры S классифицируются, а сама OOBE ошибка вычисляется как (число неверно классифицированных примеров S/ число примеров S всего). В on-line реализации это делается чуть по-другому с точки зрения алгоритма, но суть остается та же.
2. **Ошибка всего метода.** Предлагаю ее вычислять следующим методом. 
Предварительно размечаем видео (окружаем цель прямоугольной рамкой на каждом кадре и записываем координаты этих рамок на каждом кадре в некий файл). После чего измеряем отклонение рамки, которой окружается цель нашим алгоритмом, от заранее сделанной разметки. 
**Тут возникает следующий вопрос.** Как лучше вычислять отклонение одной прямоугольной рамки от другой?

Обе ошибки предлагаю считать для каждого кадра, и строить график зависимости ошибки от номера кадра.

**Comment by ioannkozlitin** [comment]
Думаю, что по расстоянию между их центрами, однако, мне кажется, что ошибку всего метода так строить не надо. Полезнее знать, какова доля кадров, где выдедяется НЕ ТОТ ПРЯМОУГОЛЬНИК.

**Comment by vladdimakov** [comment]
**Вопрос №2.** 
Могли бы вы описать структуру текста в моей ВКР?
Я пока вижу ее такой:
**Введение:** актуальность,  цели и задачи работы, содержание работы

**Глава №1:** Теоретическое обоснование детектора на основе модели фона (**без стабилизации  и без глобального фильтра шумов**) , теория случайных лесов (**не on-line**)

**Глава №2:** Существующие методы, идеи предлагаемых методов. Тут хотелось бы описать два подхода к созданию детекторов (с применением классификатора и на основе сравнения кадров).  Рассказать о том, что у обоих этих направлений есть недостатки (классификатор надо заранее обучать, а сравнение кадров, например, теряет цель при исчезновении ее из области наблюдения). И также сказать о том, что совмещение этих подходов дает высокие и стойкие результаты.
**Тут следующий вопрос:** какие именно методы рассмотреть? (ясно, что хорошо бы рассмотреть что-то на основе случайного леса, а вот что рассмотреть в качестве метода на основе сравнения кадров я не знаю)

Далее в этой же главе рассказать про наши модификации детектора на основе модели фона (стабилизация и фильтр) и модификации случайного леса (on-line), а также рассказать про их взаимодействие для самообучения.

**Глава №3** Результаты экспериментов.

**Comment by ioannkozlitin** [comment]
После обеда напишу, пока голова другим забита.

**Comment by vladdimakov** [comment]
> Думаю, что по расстоянию между их центрами, однако, мне кажется, что ошибку всего метода так строить не надо. Полезнее знать, какова доля кадров, где выдедяется НЕ ТОТ ПРЯМОУГОЛЬНИК.

Хорошо, тогда просто считать ошибку всего метода как (число кадров с неверно найденными целями / число кадров всего). Делать данный расчет для каждого кадра, чтобы показать, как со временем работа метода начинает улучшаться (классификатор обучается). Такова идея?

А по поводу метода вычисления ошибки классификатора: хороший подход?

> После обеда напишу, пока голова другим забита.

**Да, конечно, жду Вас. Приятного аппетита заранее)**

**Comment by ioannkozlitin** [comment]
Можно взять скользящее окно на 30 (может 100 и т.п.) отсчетов и на выход выдавать отношение ошибочно предскзаанных прямоугольников к длине скользящего окна. Со временем оно должно уменьшаться, если все правильно работает.

План:


Введение
1. Применение автосопровождения в жизни(видеонаблюдение, военное дело и т.п)

Глава 1. Обнаружение и сопровождение цели.
1. Виды алгоритмов обнаружения и сопровождения (кратко) : пороговые, корреляционные, вычитание фона и др.
2. Обнаружение и сопровождение на основе вычитания фона с учетом движения камеры

Глава 2. Классификация и распознавание объектов
1. Виды классификаторов
2. Решающие деревья и леса
3. Обучение на лету

Глава 3. Применение методов распознавания образов к задаче сопровождения

Глава 4. Результаты работы программы

Заключение. Перспективы дальнейшей работы.

**Comment by ioannkozlitin** [comment]
Это все довольно приблизительно, так что можно это еще пообсуждать.

**Comment by vladdimakov** [comment]
> Можно взять скользящее окно на 30 (может 100 и т.п.) отсчетов и на выход выдавать отношение ошибочно предскзаанных прямоугольников к длине скользящего окна. Со временем оно должно уменьшаться, если все правильно работает.

Можно чуть подробнее, а то не понятна идея.

Пока буду формировать текст с учетом предложенной Вами структуры. Мне она кажется вполне лаконичной.
> Обнаружение и сопровождение на основе вычитания фона с учетом движения камеры

Сюда же пишу про глобальный порог от шумов?

**Comment by ioannkozlitin** [comment]
Пусть есть следующая строка с признаками наличия ошибок на каждом кадре:

0 1 0 1 1 1 0 1 1 0 0 1 0 0 ...

Берем окно длины 3.

1. Начало: 0 1 0, ошибка 1/3
2. Сдвигаем окно вперед: 1 0 1, ошибка 2/3
3. Еще раз двигаем: 0 1 1, ошибка 2/3

и т.п.

>  Сюда же пишу про глобальный порог от шумов?

да, сюда

**Comment by vladdimakov** [comment]
Спасибо. Понял Вашу идею. Попробую реализовать.

**Comment by vladdimakov** [comment]
Иван Алексеевич, добрый день. К вам можно подъехать сегодня проставить подписи в наших зачётных книжках? Если да, то во сколько. Все 4 зачётки у меня уже на руках.

**Comment by vladdimakov** [comment]
**Иван Алексеевич, с праздником Вас!**

При написании текста ВКР у меня появился ряд вопросов:
1.  Вы писали, что одна из глав должна содержать следующую информацию
> Виды алгоритмов обнаружения и сопровождения (кратко) : пороговые, корреляционные, вычитание фона и др.

Возможно, лучше **разделить этот пункт на две части**: виды алгоритмов обнаружения (пороговые, корреляционные, вычитание фона) и виды алгоритмов сопровождения? Потому что алгоритмы (пороговые, корреляционные, вычитание фона) не являются алгоритмами сопровождения непосредственно. 

2. Откуда лучше взять информацию об алгоритмах (пороговых, корреляционных, вычитание фона)?  "Отсебятину" писать не хочется, да и не очень понимаю суть пороговых и корреляционных алгоритмов. Поиски адекватной информации по этой теме не увенчались успехом. **Может быть у Вас есть какая-то литература по этой теме?**
3. В работе я часто использую термин "последовательность кадров". Я думаю, что в контексте нашей работы совсем не стоит углубляться в суть цифровой видеозаписи (форматы, сжатие и т.д.). А стоит просто описать, что представляет собой цифровое изображение и сказать про то, что цифровое видео можно представить в виде последовательности изображений (кадров). **Это нормальная идея?**
4. Про обзор классификаторов. Я планирую описать их основные виды: Байесовские классификаторы, Нейронная сеть, Линейный разделитель и алгоритмы, основанные на индукция правил (леса и деревья решений).  При этом не углубляться в математические основы, а описать суть их алгоритмов, достоинства и недостатки. 
5. Про описание алгоритмов. В тексте ВКР хотелось бы привести 2 алгоритма: построение случайного леса и построение случайного леса "на лету". Сейчас я сделал это в виде псевдокода, но мне кажется, что это не самая лучшая визуализация структуры алгоритма. Хочу заменить псевдокод на блок-схемы. **Стоит ли?** Думаю, что благодаря этому, суть алгоритмов станет куда более понятной, да и блок-схемы можно вставить в презентацию на защите ВКР.

**Хотелось бы услышать Ваше мнение по каждому из вышеописанных вопросов.**

**Comment by ioannkozlitin** [comment]
1 - не согласен, т.к. сопровождение нередко сводится к последовательному обнаружению на последовательных кадрах при наличии априорной информации; 2 - пришлю; 3 - вполне нормальная; 4 - согласен; 5 - как хотите, если не лень - делайте. Лично мне блок-схемы не очень нравятся - любой маломайски сложный алгоритм выглядит очень громздко. Если их и делать, то как-то сокращенно, а не по ГОСТу.

**Comment by vladdimakov** [comment]
Огромное спасибо! Все учту. Жду от Вас литературу по пункту 2.

**Comment by ioannkozlitin** [comment]
Добавил книгу по сопровождению. Она, на мой взгляд, излишне математизирована, но для написания диплома, думаю, сойдет.

**Comment by vladdimakov** [comment]
Большое спасибо. Буду разбираться.

**Comment by vladdimakov** [comment]
Иван Алексеевич, добрый день. Я описал в тексте ВКР все, кроме результатов работы программы. Также еще не осуществлял разметку тех частей текста, которые цитирую. 
**Жду вашего мнения о том, что получилось, а также замечаний по структуре и  оформлению.**
Текст ВКР прилагаю. [ВКР_Димаков_В.С._МП-40.pdf](https://github.com/vladdimakov/cv2/files/1001306/_._._.-40.pdf)

**Еще немного информации.**
Предзащита наших дипломных работ состоится 24 мая, так что до этого времени необходимо дописать текст ВКР и сделать презентацию к выступлению. 
Защита состоится 15 июня.

**Comment by vladdimakov** [comment]
**Прилагаю новый, дописанный текст ВКР.** 
В нем не хватает только краткого обзора видов классификаторов и списка литературы.
**Жду вашего мнения о том, что получилось, а также замечаний по структуре и оформлению. Особенно по экспериментальной части!**
[ВКР_Димаков_В.С._МП-40.pdf](https://github.com/vladdimakov/cv2/files/1012594/_._._.-40.pdf)

**Еще информация:**
Узнал точное место и время предзащиты: 24 мая в 12:00, ауд. 1203.

**Comment by ioannkozlitin** [comment]
Презентация приличная, но ее надо ужать раза в 1.5 - до 10-12 слайдов (10 лучше), так как иначе те, кто будут Вас слушать, все равно не успеют считать всю эту информацию. Текста в ВКР довольно много - пока нет возможности детально изучить Ваш труд.

**Comment by vladdimakov** [comment]
Спасибо, Иван Алексеевич. Учту Ваши замечания.

**Comment by ioannkozlitin** [comment]
Хороший текст выступления, с грамотным использованием терминологии, а это показатель уже неплохой квалификации.

**Comment by ioannkozlitin** [comment]
Пишете хорошо, но слишком заумно, например "Он основан на формировании обучающей выборки для каждого дерева ансамбля с помощью бутстрепа и использовании невзвешенного голосования при агрегировании решений отдельных классификаторов. Бутстреп-выборкой называется случайная выборка с возвращением из исходной обучающей выборки. ".

Я бы написал это так: "Баггингом называется такой способ построения обучающей выборки случайного леса, при котором для каждого его дерева строится отдельная случайная выборка с возвращением из исходной обучающей выборки (бутстреп-выборка)."

**Comment by vladdimakov** [comment]
Да, это моя постоянная проблема - пишу сложно. Поправлю подобные моменты. А Вы дошли до 4 главы (результаты экспериментов) ?

**Comment by ioannkozlitin** [comment]
Пока нет

**Comment by vladdimakov** [comment]
Финальная версия текста ВКР
[ВКР_Димаков_В.С._МП-40.pdf](https://github.com/vladdimakov/cv2/files/1048075/_._._.-40.pdf)

**Comment by ioannkozlitin** [comment]
Дочитал Ваш текст. Все хорошо, хотя есть ряд опечаток, которые Вы сами найдете, если почитаете внимательнее свой текст. Вопрос: а Вы на видео размечали найденные вычитанием фона области вручную (по признаку цель/не цель) или как-то иначе?
